apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    heritage: deis
    version: 2.0.0-beta
spec:
  restartPolicy: Never
  containers:
    - name: deis-slugbuilder
      imagePullPolicy: Always
      image: quay.io/deisci/slugbuilder:v2-beta
      env:
        - name: TAR_URL
          value: {{.TarURL}}
        - name : put_url
          value: {{.PutURL}}
        - name: BUILDPACK_URL
          value: {{.BuildPackURL}}
